### PR TITLE
Hydrobiologie

### PR DESCRIPTION
**Pull request by LafageDenis**
Hi, 

Here is a new get function for the hydrobiologie API. 
I followed the documentation for the development. It worked pretty well except for the convert_list_to_tibble function that was giving an error due to nested lists in the API responses. I fixed this by removing the nested lists. I guess there is a more elegant way ...

### CODE REVIEW

**Comment by DDorch** [comment]
Hi @LafageDenis!

Thanks for this contribution! @PascalIrz told me yesterday that he has begun to implement this API too on his side. He currently meets some difficulties with duplicated rows in the results which maybe need some post-processing as the one I had to provide for the API hydrometrie (See BRGM explanations: https://github.com/BRGM/hubeau/issues/73).

I wait for some feed back from @PascalIrz before merging this pull-request.

**Comment by LafageDenis** [comment]
OK, sounds good !

**Comment by PascalIrz** [comment]
Hi @LafageDenis, hi @DDorch!

Sorry for this late answer, I check that ASAP.

Cheers

**Comment by PascalIrz** [comment]
> Hi @LafageDenis!
> 
> Thanks for this contribution! @PascalIrz told me yesterday that he has begun to implement this API too on his side. He currently meets some difficulties with duplicated rows in the results which maybe need some post-processing as the one I had to provide for the API hydrometrie (See BRGM explanations: [BRGM/hubeau#73](https://github.com/BRGM/hubeau/issues/73)).
> 
> Therefore, I wait for some feed back from @PascalIrz before merging this pull-request.

Hi,
Indeed my issue on the HUBEAU is : [https://github.com/BRGM/hubeau/issues/129
](https://github.com/BRGM/hubeau/issues/129
)

**Comment by DDorch** [comment]
This pull request has been replaced by the one proposed by @PascalIrz in coordination with @LafageDenis.

**Pull request closed without merging**
